### ISSUE TITLE
Cannot enable plugin

### ISSUE THREAD

**Issue by jhaws1982** [wsovalle/docker-vxcan#1]
I ran into this issue with the original can4docker and was hoping maybe you had fixed it. Alas I still have this error when I try to install/enable the plugin. I'm happy to dive in and fix it, but it would be good to have an idea where to start.

This is what I see when I try to enable or install the plugin:

```
root@imx6ullevk:~# docker plugin ls
ID             NAME                    DESCRIPTION                 ENABLED
5b5c9dc379cf   wsovalle/vxcan:latest   Provides CAN connectivity   false

root@imx6ullevk:~# docker plugin enable wsovalle/vxcan
Error response from daemon: dial unix /run/docker/plugins/5b5c9dc379cf6339120ee948a89638d3b188e0ebe1f0ddc29a81cb0775ef320c/can4docker.sock: connect: no such file or directory

root@imx6ullevk:~# docker --version
Docker version 20.10.10, build b485636f4b

root@imx6ullevk:~# uname -a
Linux imx6ullevk 5.10.93-lmp-standard #1 SMP PREEMPT Thu Jan 20 20:01:30 UTC 2022 armv7l armv7l armv7l GNU/Linux

root@imx6ullevk:~# lsmod | grep can
flexcan                28672  0
can_dev                24576  1 flexcan
vxcan                  16384  0
vcan                   16384  0
can_isotp              24576  0
can_gw                 24576  0
can                    24576  2 can_isotp,can_gw
```

For some reason it appears to be looking for the UNIX socket in the wrong location. This seems like it would be an easy fix, but I don't see where to begin.

Thanks!

**Comment by wsovalle** [comment]
Hi, thanks for information. I'll look into this issue tomorrow.

**Comment by jhaws1982** [comment]
Great!  Let me know where I can help with testing.  I'm happy to dig in (and started to) but just don't know where to begin. I wasn't even able to find where the socketAddress is getting set initially to look in the wrong folder...

**Comment by wsovalle** [comment]
It's not that easy, because path mentioned is created by docker engine (not by plugin code) as part of enabling a plugin, there are no intermediate states that could be verified.

At first glance it seems to be caused by differences between system where the plugin was built (x86/Ubuntu) and your host.
I admit I never tried it on any embedded host and don't have resources to do it atm, but the issue is totally valid.

You might try rebuilding the plugin on your host (my build scripts are messy, but available in `image/docker-plugin`, main script being `rebuild-plugin.sh`), it only requires make, docker and python afaik.

I never considered running it on any other platforms myself and didn't even think that it might be an issue, so if you find anything that could improve this project or in any way help with fixing it - let me know.

**Comment by jhaws1982** [comment]
Do you know if there is a way to grab a variable from the docker engine that has the socket path?  I see in the can4docker.sh script that the path is hardcoded:

`gunicorn -b unix:/run/docker/plugins/can4docker.sock can4docker.driver:APPLICATION`

**Comment by jhaws1982** [comment]
Okay - here are where things stand.  I was able to rebuild the plugin on my embedded target and now I can enable the plugin properly.

```
root@imx6ullevk:~/docker-vxcan# docker plugin ls
ID             NAME                    DESCRIPTION                 ENABLED
879ceb88080e   wsovalle/vxcan:latest   Provides CAN connectivity   true
```

However, when I try to create a network for a simple test (cangen from host and candump in container) it fails because it cannot find the driver:

```
root@imx6ullevk:~/docker-vxcan# docker network create -d wsovalle/vxcan:latest canbus0
Error response from daemon: could not resolve driver wsovalle/vxcan:latest in registry
```

I setup a compose app, thinking maybe I had to use that instead:
```
version: "3"
services:
  app_can0:
    image: ubuntu:20.04
    tty: true
    networks: [ canbus0 ]
networks:
  canbus0:
    driver: wsovalle/vxcan:latest
    driver_opts:
      vxcan.dev: can_host
      vxcan.peer: can_docker
      vxcan.id: 0
```

But I get this output:

```
root@imx6ullevk:~/docker-vxcan# docker-compose up
Creating network "docker-vxcan_canbus0" with driver "wsovalle/vxcan:latest"
ERROR: could not resolve driver wsovalle/vxcan:latest in registry
```

So - what would you say are the next steps?  It feels like the plugin is not registered completely with docker?  I don't have any running containers, which seems odd since isn't that what a plugin is (more or less)?

Thanks for the support!

**Comment by wsovalle** [comment]
Hi again. After enabling, a plugin should create a folder in `/run/docker/plugins`, containing `can4docker.sock`, `init-stderr` and `init-stdout`.
I'm interested in output of
```
# cat < init-stderr 
```
after `docker-compose up` or `docker network create`.

Edit: to be more precise - you need to launch `cat < init-stderr` and then perform actions.

**Comment by jhaws1982** [comment]
This is what I get from `docker plugin enable wsovalle/vxcan' and then catting the init-stderr.

```
root@imx6ullevk:/run/docker/plugins# cat < 879ceb88080edff91d598b1255a0e282dc954500c635999091edddcb74aa1450/init-stderr
[2022-02-24 16:10:32 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2022-02-24 16:10:32 +0000] [7] [INFO] Listening at: unix:/run/docker/plugins/can4docker.sock (7)
[2022-02-24 16:10:32 +0000] [7] [INFO] Using worker: sync
[2022-02-24 16:10:32 +0000] [9] [INFO] Booting worker with pid: 9
[2022-02-24 16:10:37 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.8/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/can4docker/driver.py", line 7, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.8/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/site-packages/itsdangerous/__init__.py)
[2022-02-24 16:10:37 +0000] [9] [INFO] Worker exiting (pid: 9)
[2022-02-24 16:10:37 +0000] [7] [INFO] Shutting down: Master
[2022-02-24 16:10:37 +0000] [7] [INFO] Reason: Worker failed to boot.
```

I'm looking into updating Flask to the latest (2.0.1 or better I think) to see if this can get cleared up.  If that doesn't work, I'll add a requirement to downgrade itsdangerous to 2.0.1 and maybe that will take care of it.

Unless of course you have some other ideas to try.  Thanks!

Another note - is there a way to kind of test this outside the docker environment - just to be sure the container itself is running and starting up right?

**Comment by jhaws1982** [comment]
Another update.  Upgrading Flask to >= 2.0.1 in `requirements/can4docker.txt` got it to start correctly.  Now, here is the output from init-stderr when I run: `docker network create -d jhaws1982/vxcan:latest canbus0`

```
root@imx6ullevk:/run/docker/plugins# cat < 0ec92ec5a5216d7534fd9534dff1f9d03894583fbd38e4ab976118174ea7615a/init-stderr
[2022-02-24 17:27:13 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2022-02-24 17:27:13 +0000] [7] [INFO] Listening at: unix:/run/docker/plugins/can4docker.sock (7)
[2022-02-24 17:27:13 +0000] [7] [INFO] Using worker: sync
[2022-02-24 17:27:13 +0000] [9] [INFO] Booting worker with pid: 9
DEBUG:can4docker.driver:/NetworkDriver.GetCapabilities
DEBUG:can4docker.driver:200, {'Scope': 'local'}
DEBUG:can4docker.driver:/NetworkDriver.CreateNetwork: {'NetworkID': '5a4686af7ae8cf06a01406d62408cfa8c687126ee8da1e7209e25149c2d6cd77', 'Options': {'com.docker.network.enable_ipv6': False, 'com.docker.network.generic': {}}, 'IPv4Data': [{'AddressSpace': 'LocalDefault', 'Gateway': '172.19.0.1/16', 'Pool': '172.19.0.0/16'}], 'IPv6Data': []}
DEBUG:can4docker.driver:400, {'Err': "Failed to create the network 5a4686af7ae8cf06a01406d62408cfa8c687126ee8da1e7209e25149c2d6cd77 : (34, 'Result not representable')"}
```

**Comment by jhaws1982** [comment]
Okay - I think I have it all figured out. I'm opening a PR with my changes.

Bottom line is the upgrade to Flask got it working. I also upgraded the rest of the packages and migrated to NDB from IPDB since IPDB is deprecated in pyroute2 and cleaned up the rebuild script just a little.

I've found a few other bugs I'm working through and when those are fixed I'll submit PRs for them as well.

Thanks for the help!

**Comment by jhaws1982** [comment]
Pull request #2 is open!

**Comment by wsovalle** [comment]
Looks good, thanks for your help.

**Comment by jhaws1982** [comment]
NP!  I've got two more PRs coming, I'm just submitting them one by one.  #3 deals with CAN FD vs regular CAN traffic rules in cangw and the next one allows for utilizing preexisting CAN interfaces (such as predefined vcan or pyhsical CAN devices).

**Comment by jhaws1982** [comment]
Any thoughts on the open PR #3?  Once that one is merged I've got one more coming and then things are working to what I need this to do.

**Comment by jhaws1982** [comment]
Just wanted to reach out again and see if these updates are ones you want to pull in?

**Comment by wsovalle** [comment]
I'm sorry, I had no time to look into this recently. Will do.

**Comment by jhaws1982** [comment]
Just wanted to touch base again on whether you had time to look at these PRs? I'd prefer to pull from your upstream repo rather than my own for my projects making use of this plugin.  Thanks for your support!

**Comment by jhaws1982** [comment]
@wsovalle I think the PR that addresses this issue is ready to go. Once merged we can close this ticket.  Thanks!

**Comment by wsovalle** [comment]
Hi. Sorry for not responding for so long, but my daughter was born in August and I didn't have enough time to check it properly.
The issue is that I tried different approaches and couldn't get it to work on x86 (and I have no Yocto/i.MX nor similar platform to test).

But to the point - about a month ago I discovered that dependencies are floating and the plugin changes from build to build making my whole investigation useless. I made tests and found that `pyroute2 = 0.6.9` gives most stable results for both x86 and ARM and is still compatible with original code, so I decided to fix it to this version.

From this point I can try to look into it again, but at least pyroute2 has to have a fixed version, because otherwise it just stops to build correctly after a month or two from release.

**Comment by jhaws1982** [comment]
No worries. As it turns out, I found the python implementation to be way to slow on startup (took close to 45 seconds to get everything loaded and running). 

So I rewrote the plugin in Rust and it works great. You can find it [here](https://github.com/jhaws1982/rustycan4docker) if you want to use it. 

Thanks for the support!

**Comment by wsovalle** [comment]
Wow, great! I love the idea. Thanks for the info.
